version: '3.8'

services:
  node:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./vue:/app
    working_dir: /app
    command: npm run dev -- --host
